/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellogit_GitMainActivity */

#ifndef _Included_com_example_hellogit_GitMainActivity
#define _Included_com_example_hellogit_GitMainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellogit_GitMainActivity
 * Method:    stringFirst
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellogit_GitMainActivity_stringFirst
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_hellogit_GitMainActivity
 * Method:    stringSecond
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellogit_GitMainActivity_stringSecond
  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
